# GitHub action to publish Doxygen-based documentation

name: Generate and deploy Doxygen documentation

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ main ]

permissions:
  contents: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v3
        
    - name: Generate Doxygen documentation
      uses: mattnotmitt/doxygen-action@v1.1.0
      with:
        # Working directory
        working-directory: "Documentation/" # default is .
        # Path to Doxyfile
        doxyfile-path: "./Doxyfile" # default is ./Doxyfile
    
    - name: Deploy documentation to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        # Default Doxyfile build documentation to html directory. 
        # Change the directory if changes in Doxyfile. Original was ./html
        publish_dir: ./docs
